name: Scrape and Post to Blogger

on:
  schedule:
    - cron: '0 0 * * *'  # هر روز ساعت 00:00 UTC
  workflow_dispatch:      # امکان اجرای دستی

jobs:
  scrape-and-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4 google-auth-oauthlib google-api-python-client

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | grep -oE "[0-9]+.[0-9]+.[0-9]+")
          wget -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})/chromedriver_linux64.zip"
          unzip /tmp/chromedriver.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

      - name: Run script
        env:
          BLOGGER_CREDENTIALS: ${{ secrets.CREDENTIALS }}  # اسم Secret شما
          BLOG_ID: ${{ secrets.BLOG_ID }}
        run: |
          python au-p.py > output.log 2>&1

      - name: Upload output log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: script-output
          path: output.log
