name: Scrape and Post to Blogger

on:
  schedule:
    - cron: '0 0 * * *'  # هر روز ساعت 00:00 UTC
  workflow_dispatch:      # امکان اجرای دستی

jobs:
  scrape-and-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4 google-auth-oauthlib google-api-python-client

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          # نصب ChromeDriver نسخه 135.0.7049.42
          wget -O /tmp/chromedriver.zip "https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.42/linux64/chromedriver-linux64.zip"
          unzip /tmp/chromedriver.zip -d /tmp/
          sudo mv /tmp/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          # چک کردن نسخه‌ها
          google-chrome --version
          chromedriver --version

      - name: Run script
        env:
          BLOGGER_CREDENTIALS: ${{ secrets.CREDENTIALS }}
          BLOG_ID: ${{ secrets.BLOG_ID }}
        run: |
          echo "شروع اجرای اسکریپت..." > output.log
          python au-p.py >> output.log 2>&1 || echo "اسکریپت با خطا متوقف شد" >> output.log
          cat output.log

      - name: Upload output log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: script-output
          path: output.log
          if-no-files-found: warn
          
