name: Test WordPress Post

on:
  push: # این ورک‌فلو با هر push به ریپازیتوری اجرا می‌شود
    branches:
      - main # یا هر شاخه دیگری که می‌خواهید در آن push ها را رصد کنید

  workflow_dispatch: # این خط باعث می‌شود دکمه "Run workflow" در UI گیت‌هاب ظاهر شود
    # می‌توانید ورودی‌های اختیاری برای اجرای دستی تعریف کنید، مثال:
    # inputs:
    #   logLevel:
    #     description: 'Log level'
    #     required: true
    #     default: 'warning'
    #     type: choice
    #     options:
    #       - info
    #       - warning
    #       - debug

jobs:
  post-to-wordpress:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests feedparser beautifulsoup4

    - name: Change DNS (اختیاری - برای رفع مشکلات خاص شبکه)
      run: |
        echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
        echo "nameserver 8.8.4.4" | sudo tee -a /etc/resolv.conf
        echo "DNS servers configured. Current /etc/resolv.conf:"
        sudo cat /etc/resolv.conf

    - name: Run Python script
      env:
        WORDPRESS_URL: ${{ secrets.WORDPRESS_URL }}
        WORDPRESS_USER: ${{ secrets.WORDPRESS_USER }}
        WORDPRESS_PASS: ${{ secrets.WORDPRESS_PASS }}
        GEMAPI: ${{ secrets.GEMAPI }}
      run: python au-p.py
