name: Test WordPress Post

on:
  # این خط باعث می‌شود دکمه "Run workflow" در UI گیت‌هاب ظاهر شود (برای اجرای دستی)
  workflow_dispatch:

  # --- این بخش را اضافه یا ویرایش کنید تا هر 1 ساعت اجرا شود ---
  schedule:
    # هر ساعت در دقیقه 0 (یعنی در راس هر ساعت) اجرا می‌شود.
    # مثال: 00:00, 01:00, 02:00, ..., 23:00 UTC
    - cron: '0 * * * *'
  # --- پایان بخش جدید/ویرایش شده ---

  # اگر نمی‌خواهید با هر push هم اجرا شود، بخش push را حذف کنید یا کامنت کنید:
  # push:
  #   branches:
  #     - main

jobs:
  post-to-wordpress:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests feedparser beautifulsoup4

    - name: Change DNS (اختیاری - برای رفع مشکلات خاص شبکه)
      run: |
        echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
        echo "nameserver 8.8.4.4" | sudo tee -a /etc/resolv.conf
        echo "DNS servers configured. Current /etc/resolv.conf:"
        sudo cat /etc/resolv.conf

    - name: Run Python script
      env:
        WORDPRESS_MAIN_URL: ${{ secrets.WORDPRESS_MAIN_URL }}
        WORDPRESS_USER: ${{ secrets.WORDPRESS_USER }}
        WORDPRESS_PASS: ${{ secrets.WORDPRESS_PASS }}
        GEMAPI: ${{ secrets.GEMAPI }}
      run: python au-p.py
